#!/bin/sh
# check-no-ai-attribution.sh
#
# Scan commit messages, staged files, arbitrary files, inline text, or the
# current git identity for AI / bot attribution markers. The repo policy
# (CLAUDE.md "No AI attribution policy") forbids these strings in commits,
# PR bodies, code, and docs.
#
# Usage:
#   scripts/check-no-ai-attribution.sh --commit <ref>
#   scripts/check-no-ai-attribution.sh --staged
#   scripts/check-no-ai-attribution.sh --file <path>
#   scripts/check-no-ai-attribution.sh --text "<inline string>"
#   scripts/check-no-ai-attribution.sh --identity
#
# Exit codes:
#   0  no forbidden marker found
#   1  internal / argument error
#   2  forbidden marker found
#
# Allowlist:
#   When scanning a --file, paths that legitimately describe the policy
#   are exempt (this guard's own source, the workflow doc, the policy
#   section in CLAUDE.md, and the test file). Commit messages, PR bodies,
#   --text input, and --identity are NEVER allowlisted.

set -u

EXIT_OK=0
EXIT_ERR=1
EXIT_FORBIDDEN=2

# Forbidden fixed strings, one per line. Used with `grep -F`.
FORBIDDEN_PATTERNS='Co-Authored-By: Claude
Co-authored-by: Claude
co-authored-by: claude
Generated with Claude
Generated by Claude
generated with claude
generated by claude
Created by Claude
Authored by Claude
Claude Code generated
🤖 Generated
🤖 generated'

# Identity-level forbidden substrings (case-insensitive).
IDENTITY_PATTERNS='claude
anthropic'

# Repo-relative paths exempt from --file scans because they describe the policy.
ALLOWLIST='CLAUDE.md
docs/dev/pr_workflow.md
scripts/check-no-ai-attribution.sh
tests/test_no_ai_attribution.py
tests/test_git_hooks.py'

usage() {
    cat >&2 <<'EOF'
usage: check-no-ai-attribution.sh [MODE]

modes:
  --commit <ref>     scan the commit message AND identity at <ref> (e.g. HEAD)
  --staged           scan all staged files (skips allowlisted policy files)
  --file <path>      scan the contents of a single file
  --text "<str>"     scan the given literal string
  --identity         scan current git config user.name and user.email
  --help             show this message
EOF
}

# Normalize a possibly-absolute path to repo-relative if it is under cwd.
_norm() {
    p="$1"
    case "$p" in
        ./*) p="${p#./}" ;;
    esac
    case "$p" in
        /*)
            cwd_real=$(cd "$(pwd)" 2>/dev/null && pwd -P)
            d=$(cd "$(dirname "$p")" 2>/dev/null && pwd -P || true)
            if [ -n "$d" ]; then
                full="$d/$(basename "$p")"
                case "$full" in
                    "$cwd_real"/*) p="${full#$cwd_real/}" ;;
                esac
            fi
            ;;
    esac
    printf '%s' "$p"
}

_is_allowlisted() {
    target=$(_norm "$1")
    printf '%s\n' "$ALLOWLIST" | while IFS= read -r ok; do
        [ -z "$ok" ] && continue
        if [ "$target" = "$ok" ]; then
            return 0
        fi
    done
    # subshell return doesn't propagate; recompute with grep instead.
    if printf '%s\n' "$ALLOWLIST" | grep -F -x -q -- "$target"; then
        return 0
    fi
    return 1
}

# Scan a file. Echoes "label\tpattern\tline" findings to stdout.
# Returns count of files-with-findings via stdout last line: __FINDING_COUNT__=<n>
# Simpler convention: write findings; caller checks if findings file is non-empty.
_scan_stream() {
    label="$1"
    findings_file="$2"
    # stdin is the content to scan; pre-buffer to a temp so we can grep multiple patterns.
    buf=$(mktemp)
    cat > "$buf"
    printf '%s\n' "$FORBIDDEN_PATTERNS" | while IFS= read -r pat; do
        [ -z "$pat" ] && continue
        # grep -F -n: literal, line numbered. Allow no match without failing.
        matches=$(grep -F -n -e "$pat" "$buf" || true)
        if [ -n "$matches" ]; then
            printf '%s\n' "$matches" | while IFS= read -r m; do
                printf '%s\t%s\t%s\n' "$label" "$pat" "$m" >> "$findings_file"
            done
        fi
    done
    rm -f "$buf"
}

_check_identity_value() {
    label="$1"
    ident="$2"
    findings_file="$3"
    ident_lower=$(printf '%s' "$ident" | tr '[:upper:]' '[:lower:]')
    printf '%s\n' "$IDENTITY_PATTERNS" | while IFS= read -r pat; do
        [ -z "$pat" ] && continue
        if printf '%s' "$ident_lower" | grep -F -q -e "$pat"; then
            printf '%s\t%s\t%s\n' "$label" "$pat" "$ident" >> "$findings_file"
        fi
    done
}

_report_and_exit() {
    findings_file="$1"
    if [ -s "$findings_file" ]; then
        echo "check-no-ai-attribution: FORBIDDEN attribution detected:" >&2
        cat "$findings_file" >&2
        rm -f "$findings_file"
        exit $EXIT_FORBIDDEN
    fi
    rm -f "$findings_file"
    exit $EXIT_OK
}

cmd_commit() {
    ref="$1"
    if ! git rev-parse --verify "$ref" >/dev/null 2>&1; then
        echo "check-no-ai-attribution: invalid commit ref: $ref" >&2
        exit $EXIT_ERR
    fi
    findings=$(mktemp)
    git log -1 --format=%B "$ref" | _scan_stream "commit:$ref:message" "$findings"
    an=$(git log -1 --format=%an "$ref")
    ae=$(git log -1 --format=%ae "$ref")
    cn=$(git log -1 --format=%cn "$ref")
    ce=$(git log -1 --format=%ce "$ref")
    _check_identity_value "commit:$ref:author" "$an <$ae>" "$findings"
    _check_identity_value "commit:$ref:committer" "$cn <$ce>" "$findings"
    _report_and_exit "$findings"
}

cmd_staged() {
    if ! git rev-parse --git-dir >/dev/null 2>&1; then
        echo "check-no-ai-attribution: not a git repo" >&2
        exit $EXIT_ERR
    fi
    files=$(git diff --cached --name-only --diff-filter=ACMR)
    if [ -z "$files" ]; then
        echo "check-no-ai-attribution: no staged files" >&2
        exit $EXIT_OK
    fi
    findings=$(mktemp)
    printf '%s\n' "$files" | while IFS= read -r f; do
        [ -z "$f" ] && continue
        if _is_allowlisted "$f"; then
            continue
        fi
        blob=$(git ls-files -s -- "$f" | awk '{print $2}')
        [ -z "$blob" ] && continue
        git cat-file -p "$blob" | _scan_stream "staged:$f" "$findings"
    done
    _report_and_exit "$findings"
}

cmd_file() {
    path="$1"
    if [ ! -f "$path" ]; then
        echo "check-no-ai-attribution: file not found: $path" >&2
        exit $EXIT_ERR
    fi
    rel=$(_norm "$path")
    if _is_allowlisted "$rel"; then
        echo "check-no-ai-attribution: $rel is allowlisted (policy doc)" >&2
        exit $EXIT_OK
    fi
    findings=$(mktemp)
    cat "$path" | _scan_stream "file:$rel" "$findings"
    _report_and_exit "$findings"
}

cmd_text() {
    text="$1"
    findings=$(mktemp)
    printf '%s' "$text" | _scan_stream "text:inline" "$findings"
    _report_and_exit "$findings"
}

cmd_identity() {
    name=$(git config user.name 2>/dev/null || echo "")
    email=$(git config user.email 2>/dev/null || echo "")
    if [ -z "$name" ] || [ -z "$email" ]; then
        echo "check-no-ai-attribution: git config user.name / user.email is unset" >&2
        exit $EXIT_FORBIDDEN
    fi
    findings=$(mktemp)
    _check_identity_value "identity:current" "$name <$email>" "$findings"
    _report_and_exit "$findings"
}

if [ $# -lt 1 ]; then
    usage
    exit $EXIT_ERR
fi

case "$1" in
    --commit)
        [ $# -lt 2 ] && { usage; exit $EXIT_ERR; }
        cmd_commit "$2"
        ;;
    --staged)
        cmd_staged
        ;;
    --file)
        [ $# -lt 2 ] && { usage; exit $EXIT_ERR; }
        cmd_file "$2"
        ;;
    --text)
        [ $# -lt 2 ] && { usage; exit $EXIT_ERR; }
        cmd_text "$2"
        ;;
    --identity)
        cmd_identity
        ;;
    --help|-h)
        usage
        exit $EXIT_OK
        ;;
    *)
        usage
        exit $EXIT_ERR
        ;;
esac
